package eirvid.master.model;

import java.math.BigDecimal;
import java.util.Objects;

/**
 *
 * @author alessandracaballero
 * student number: 2021258
 */

public class Movie {
    
    public Movie() {
    }

    
    //Variables from each collum in the file .csv
    private Long Id;
    private String nameMovie;
    private String categoryMovie;
    private String yearMovie;
    private String price;

    // Getters and Setters
    public Long getId() {
        return Id;
    }

    public void setId(Long Id) {
        this.Id = Id;
    }

    public String getNameMovie() {
        return nameMovie;
    }

    public void setNameMovie(String nameMovie) {
        this.nameMovie = nameMovie;
    }

    public String getCategoryMovie() {
        return categoryMovie;
    }

    public void setCategoryMovie(String categoryMovie) {
        this.categoryMovie = categoryMovie;
    }

    public String getYearMovie() {
        return yearMovie;
    }

    public void setYearMovie(String yearMovie) {
        this.yearMovie = yearMovie;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    // HashCode generated by Netbeans
    @Override
    public int hashCode() {
        int hash = 3;
        return hash;
    }

    // Equals generated by Netbeans
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Movie other = (Movie) obj;
        return Objects.equals(this.Id, other.Id);
    }

    // ToString generated by Netbeans
    @Override
    public String toString() {
        return "Movies{" + "Id=" + Id + ", nameMovie=" + nameMovie + ", categoryMovie=" + categoryMovie + ", yearMovie=" + yearMovie + ", price=" + price + '}';
    }

    // Constructor generated by Netbeans
    public Movie(Long Id, String nameMovie, String categoryMovie, String yearMovie, String price) {
        this.Id = Id;
        this.nameMovie = nameMovie;
        this.categoryMovie = categoryMovie;
        this.yearMovie = yearMovie;
        this.price = price;
    }  
}
